FROM mcr.microsoft.com/dotnet/core/sdk as build
WORKDIR /data
COPY . .
RUN dotnet build
RUN dotnet publish --no-restore -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet
WORKDIR /dist
EXPOSE 5000
EXPOSE 5432
# EXPOSE 5001
ENV ASPNETCORE_URLS=http://*:5000
COPY --from=build /data/out .
CMD [ "dotnet", "RestApi.Client.dll" ]